# NOTE: Dockerfile.dev for project development
# base image
FROM node:alpine

# define working directory
WORKDIR '/app'

# install dependecies
COPY package.json .
RUN npm install

# NOTE: due to "create-react-app projectname" command, it has automatically installed all the dependencies (node_module folder). 
# previously we never defined dependencies inside our project, but we used docker to install it when initially the image is created. 
# So we have duplicate dependencies, which is not reliable. We will delete that extra folder(node_modules).
COPY . .

#start-up command
CMD ["npm","run","start"]